name: DevCard

permissions:
  contents: write
on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * 0"  # Weekly on Sunday at 01:00 UTC

jobs:
  devcard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: devcard
        uses: dailydotdev/action-devcard@2.0.4
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
      
      - name: Move to images directory
        run: |
          mkdir -p images
          mv devcard.svg images/devcard.svg || true
      
      - name: Commit & Push
        run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git add images/devcard.svg
          git commit -m "Update DevCard" || exit 0
          git push

